# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 682d610ca8aa2ad44cd2e7ac58132a610393ea2ce0a8d293418870867913138ede11d12e715cf519cb7d315b5a8ddf661944e5ad03b1c0d22f5a67a96f37fbc1

test:
  secret_key_base: 6b60d225f92ae44cbffafa43ce017de8b547d75b24bebc44a2bdd7f0b04aa6f67abfe3d1a6806555985077121bcaa5c4ca1d2c707dfbe183583173f0bf12090d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
